---
# tasks file for web-server
- name: make sure nginx is installed
  hosts: all
  become: yes
  yum: "name={{ item }} state=present"
  with_items:
    - nginx

- name: make sure nginx is running
  service: "name=nginx state=running"
