---
# tasks file for web-server
- name: make sure nginx is installed
  hosts: all
  become: yes
  yum:
    name=nginx
    state=latest:

- name: make sure nginx is running
  service: "name=nginx state=running"
