---
- name: make sure nginx is installed
  hosts: all
  become: yes
  
  tasks:
  - name: Install nginx
    yum: name=docker state=latest

  - name: make sure nginx is running
    service: name=docker state=started enabled=yes
